app_ar = {
    "login_failed": "فشل تسجيل الدخول",
    "invalid_username_password": "اسم مستخدم أو كلمة مرور غير صالحة",
    "invalid_option": "يرجى اختيار وضع صحيح: المشرف أو الموظف",
    "admin_title": "المشرف",
    "search": "بحث",
    "name": "الاسم",
    "phone": "الهاتف",
    "email": "البريد الإلكتروني",
    "file": "ملف",
    "new_file": "ملف جديد",
    "open_file": "فتح الملف",
    "help": "مساعدة",
    "address": "العنوان",
    "state": "الولاية",
    "birth_date": "تاريخ الميلاد",
    "mobile_number": "رقم الجوال",
    "national_id": "الرقم القومي",
    "education_year": "سنة التعليم",
    "school_name": "اسم المدرسة",
    "level": "المستوى",
    "faculty": "الكلية",
    "college": "الجامعة",
    "graduation_year": "سنة التخرج",
    "job": "الوظيفة",
    "workplace": "مكان العمل",
    "blood_type": "فصيلة الدم",
    "skills": "المهارات",
    "club_member": "عضو في النادي",
    "club_name": "اسم النادي",
    "has_car": "يمتلك سيارة",
    "car_participation": "مشاركة السيارة"
}