app_en = {
    "login_failed": "Login Failed",
    "invalid_username_password": "Invalid Username or password",
    "invalid_option": "Please select a valid mode: Admin or Employee",
    "admin_title": "Admin",
    "search": "Search",
    "name": "Name",
    "phone": "Phone",
    "email": "Email",
    "file": "File",
    "new_file": "New File",
    "open_file": "Open File",
    "help": "Help",
    "address": "Address",
    "state": "State",
    "birth_date": "Birth Date",
    "mobile_number": "Mobile Number",
    "national_id": "National ID",
    "education_year": "Education Year",
    "school_name": "School Name",
    "level": "Level",
    "faculty": "Faculty",
    "college": "College",
    "graduation_year": "Year of Graduation",
    "job": "Job",
    "workplace": "Workplace",
    "blood_type": "Blood Type",
    "skills": "Skills",
    "club_member": "Club Member",
    "club_name": "Club Name",
    "has_car": "Has Car",
    "car_participation": "Car Participation"
}

